name: Release
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: blog
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install Packages
        run: node ../common/scripts/install-run-rush.js install
      - name: Build
        run: node ../common/scripts/install-run-rush.js build
      - name: Test
        run: node ../common/scripts/install-run-rush.js test
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::112125362830:role/AccessStack-GitHubDeploymentRoleD4E2A70A-13MOYB8GA6649
          role-session-name: GitHubDeploymentSession
          aws-region: eu-central-1
      - name: Release
        run: node ../common/scripts/install-run-rush.js release
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
