name: Test
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: blog
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install Packages
        run: node ../common/scripts/install-run-rush.js install
      - name: Build
        run: node ../common/scripts/install-run-rush.js build
      - name: Test
        run: node ../common/scripts/install-run-rush.js test
