name: Test and build
on:
  pull_request:
    branches:
      - main

jobs:
  testAndBuild:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: blog
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install Packages
        run: npm install --prefer-offline --no-audit
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/blog/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - name: Test and build
        run: npx concurrently -s -n "test,build" "npm test" "npm run build"
